### ISSUE TITLE
Online Tutorials resource

### ISSUE THREAD

**Issue by mssiraj** [shadow/shadow-plugin-bitcoin#16]
Hi all,
Please, is there any online resource (preferably video) for us to learn how to build apps (plugins) to work with Shadow from scratch?

Can I build an app (or a plugin) in Python and run it in Shadow? If yes, how and any online resource?

Yes, I have seen the Hello world app but I think it's too difficult to understand especially being in C/C++. I can bootstrap the XML file for the nodes but really need help on the plugin. I couldn't find what I need online.

**Comment by robgjansen** [comment]
There is no video or tutorial about how to build plugins generally. A plugin in Shadow should work like any application you would build, except with some special compilation procedures.

The hello world example will be the easiest example of creating a plugin. It provides a template code that you could start with and then modify for your purposes.
https://github.com/shadow/shadow-plugin-extras/tree/master/hello

Shadow only supports C/C++ at the moment, so if you can't write your code in C/C++ then Shadow probably won't work well for you. There has been some work in trying to get python code running in Shadow, but it involves some complexities that I don't think have been ironed out yet and certainly haven't been tested.
https://github.com/shadow/shadow-plugin-extras/tree/master/python

Shadow is an open source project that currently doesn't have any full time developers dedicated to working on it, so you may have to do some extra work to get things working or else look at other solutions. Sorry, hope that helps!

**Comment by mssiraj** [comment]
T

> 
> 
> There is no video or tutorial about how to build plugins generally. A plugin in Shadow should work like any application you would build, except with some special compilation procedures.
> 
> The hello world example will be the easiest example of creating a plugin. It provides a template code that you could start with and then modify for your purposes.
> https://github.com/shadow/shadow-plugin-extras/tree/master/hello
> 
> Shadow only supports C/C++ at the moment, so if you can't write your code in C/C++ then Shadow probably won't work well for you. There has been some work in trying to get python code running in Shadow, but it involves some complexities that I don't think have been ironed out yet and certainly haven't been tested.
> https://github.com/shadow/shadow-plugin-extras/tree/master/python
> 
> Shadow is an open source project that currently doesn't have any full time developers dedicated to working on it, so you may have to do some extra work to get things working or else look at other solutions. Sorry, hope that helps!

**Comment by mssiraj** [comment]
Dear Jansen.
Thank you very much.
I am grateful.
