### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by Frankenmint** [shadow/shadow-plugin-bitcoin#3]
$ make -j2
[  1%] [ 11%] Built target shadow-boost-bitcode
Building LLVM bitcode init.cpp.bc
[ 26%] Built target shadow-leveldb-bitcode
[ 27%] Built target shadow-plugin-bitcoind-bitcode
[ 27%] Built target LLVMHoistGlobals
[ 27%] Built target generate_pth
[ 28%] Built target shadow-preload-bitcoind
[ 38%] Built target shadow-pth-bitcode
[ 38%] Building LLVM bitcode main.cpp.bc
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.cpp:46:1: error: 
      reference to 'int64_t' is ambiguous
int64_t nTimeBestReceived = 0;
^
/usr/include/x86_64-linux-gnu/sys/types.h:197:1: note: candidate found by name
      lookup is 'int64_t'
**intN_t (64, __DI**);
^
/usr/include/x86_64-linux-gnu/sys/types.h:188:15: note: expanded from macro
      '**intN_t'
  typedef int int##N##_t __attribute** ((**mode** (MODE)))
              ^
<scratch space>:154:1: note: expanded from here
int64_t
^
/home/frankenmint/shadow-plugin-bitcoin/build/boost_1_50_0/boost/cstdint.hpp:308:50: note: 
      candidate found by name lookup is 'boost::int64_t'
     typedef  ::boost::long_long_type            int64_t;
                                                 ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.cpp:46:9: error: 
      redefinition of 'nTimeBestReceived' with a different type: 'int64_t'
      (aka 'long long') vs 'int64_t' (aka 'long')
int64_t nTimeBestReceived = 0;
        ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.h:94:16: note: 
      previous definition is here
extern int64_t nTimeBestReceived;
               ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.cpp:55:1: error: 
      reference to 'int64_t' is ambiguous
int64_t CTransaction::nMinTxFee = 10000;  // Override with -mintxfee
^
/usr/include/x86_64-linux-gnu/sys/types.h:197:1: note: candidate found by name
      lookup is 'int64_t'
**intN_t (64, __DI**);
^
/usr/include/x86_64-linux-gnu/sys/types.h:188:15: note: expanded from macro
      '**intN_t'
  typedef int int##N##_t __attribute** ((**mode** (MODE)))
              ^
<scratch space>:154:1: note: expanded from here
int64_t
^
/home/frankenmint/shadow-plugin-bitcoin/build/boost_1_50_0/boost/cstdint.hpp:308:50: note: 
      candidate found by name lookup is 'boost::int64_t'
     typedef  ::boost::long_long_type            int64_t;
                                                 ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.cpp:55:23: error: 
      redefinition of 'nMinTxFee' with a different type: 'int64_t'
      (aka 'long long') vs 'int64_t' (aka 'long')
int64_t CTransaction::nMinTxFee = 10000;  // Override with -mintxfee
                      ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/core.h:186:20: note: 
      previous definition is here
    static int64_t nMinTxFee;
                   ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.cpp:57:1: error: 
      reference to 'int64_t' is ambiguous
int64_t CTransaction::nMinRelayTxFee = 1000;
^
/usr/include/x86_64-linux-gnu/sys/types.h:197:1: note: candidate found by name
      lookup is 'int64_t'
**intN_t (64, __DI**);
^
/usr/include/x86_64-linux-gnu/sys/types.h:188:15: note: expanded from macro
      '**intN_t'
  typedef int int##N##_t __attribute** ((**mode** (MODE)))
              ^
<scratch space>:154:1: note: expanded from here
int64_t
^
/home/frankenmint/shadow-plugin-bitcoin/build/boost_1_50_0/boost/cstdint.hpp:308:50: note: 
      candidate found by name lookup is 'boost::int64_t'
     typedef  ::boost::long_long_type            int64_t;
                                                 ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.cpp:57:23: error: 
      redefinition of 'nMinRelayTxFee' with a different type: 'int64_t'
      (aka 'long long') vs 'int64_t' (aka 'long')
int64_t CTransaction::nMinRelayTxFee = 1000;
                      ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/core.h:187:20: note: 
      previous definition is here
    static int64_t nMinRelayTxFee;
                   ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.cpp:120:9: error: 
      reference to 'int64_t' is ambiguous
        int64_t nTime;  // Time of "getdata" request in microseconds.
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:197:1: note: candidate found by name
      lookup is 'int64_t'
**intN_t (64, __DI**);
^
/usr/include/x86_64-linux-gnu/sys/types.h:188:15: note: expanded from macro
      '**intN_t'
  typedef int int##N##_t __attribute** ((**mode** (MODE)))
              ^
<scratch space>:154:1: note: expanded from here
int64_t
^
/home/frankenmint/shadow-plugin-bitcoin/build/boost_1_50_0/boost/cstdint.hpp:308:50: note: 
      candidate found by name lookup is 'boost::int64_t'
     typedef  ::boost::long_long_type            int64_t;
                                                 ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.cpp:212:5: error: 
      reference to 'int64_t' is ambiguous
    int64_t nLastBlockReceive;
    ^
/usr/include/x86_64-linux-gnu/sys/types.h:197:1: note: candidate found by name
      lookup is 'int64_t'
**intN_t (64, __DI**);
^
/usr/include/x86_64-linux-gnu/sys/types.h:188:15: note: expanded from macro
      '**intN_t'
  typedef int int##N##_t __attribute** ((**mode** (MODE)))
              ^
<scratch space>:154:1: note: expanded from here
int64_t
^
/home/frankenmint/shadow-plugin-bitcoin/build/boost_1_50_0/boost/cstdint.hpp:308:50: note: 
      candidate found by name lookup is 'boost::int64_t'
     typedef  ::boost::long_long_type            int64_t;
                                                 ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.cpp:213:5: error: 
      reference to 'int64_t' is ambiguous
    int64_t nLastBlockProcess;
    ^
/usr/include/x86_64-linux-gnu/sys/types.h:197:1: note: candidate found by name
      lookup is 'int64_t'
**intN_t (64, __DI**);
^
/usr/include/x86_64-linux-gnu/sys/types.h:188:15: note: expanded from macro
      '**intN_t'
  typedef int int##N##_t __attribute** ((**mode** (MODE)))
              ^
<scratch space>:154:1: note: expanded from here
int64_t
^
/home/frankenmint/shadow-plugin-bitcoin/build/boost_1_50_0/boost/cstdint.hpp:308:50: note: 
      candidate found by name lookup is 'boost::int64_t'
     typedef  ::boost::long_long_type            int64_t;
                                                 ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.cpp:559:58: error: 
      reference to 'int64_t' is ambiguous
bool IsFinalTx(const CTransaction &tx, int nBlockHeight, int64_t nBlockTime)
                                                         ^
/usr/include/x86_64-linux-gnu/sys/types.h:197:1: note: candidate found by name
      lookup is 'int64_t'
**intN_t (64, __DI**);
^
/usr/include/x86_64-linux-gnu/sys/types.h:188:15: note: expanded from macro
      '**intN_t'
  typedef int int##N##_t __attribute** ((**mode** (MODE)))
              ^
<scratch space>:154:1: note: expanded from here
int64_t
^
/home/frankenmint/shadow-plugin-bitcoin/build/boost_1_50_0/boost/cstdint.hpp:308:50: note: 
      candidate found by name lookup is 'boost::int64_t'
     typedef  ::boost::long_long_type            int64_t;
                                                 ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.cpp:569:10: error: 
      reference to 'int64_t' is ambiguous
    if ((int64_t)tx.nLockTime < ((int64_t)tx.nLockTime < LOCKTIME_THRESH...
         ^
/usr/include/x86_64-linux-gnu/sys/types.h:197:1: note: candidate found by name
      lookup is 'int64_t'
**intN_t (64, __DI**);
^
/usr/include/x86_64-linux-gnu/sys/types.h:188:15: note: expanded from macro
      '**intN_t'
  typedef int int##N##_t __attribute** ((**mode** (MODE)))
              ^
<scratch space>:154:1: note: expanded from here
int64_t
^
/home/frankenmint/shadow-plugin-bitcoin/build/boost_1_50_0/boost/cstdint.hpp:308:50: note: 
      candidate found by name lookup is 'boost::int64_t'
     typedef  ::boost::long_long_type            int64_t;
                                                 ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.cpp:569:10: error: 
      reference to 'int64_t' is ambiguous
    if ((int64_t)tx.nLockTime < ((int64_t)tx.nLockTime < LOCKTIME_THRESH...
         ^
/usr/include/x86_64-linux-gnu/sys/types.h:197:1: note: candidate found by name
      lookup is 'int64_t'
**intN_t (64, __DI**);
^
/usr/include/x86_64-linux-gnu/sys/types.h:188:15: note: expanded from macro
      '**intN_t'
  typedef int int##N##_t __attribute** ((**mode** (MODE)))
              ^
<scratch space>:154:1: note: expanded from here
int64_t
^
/home/frankenmint/shadow-plugin-bitcoin/build/boost_1_50_0/boost/cstdint.hpp:308:50: note: 
      candidate found by name lookup is 'boost::int64_t'
     typedef  ::boost::long_long_type            int64_t;
                                                 ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.cpp:569:35: error: 
      reference to 'int64_t' is ambiguous
    if ((int64_t)tx.nLockTime < ((int64_t)tx.nLockTime < LOCKTIME_THRESH...
                                  ^
/usr/include/x86_64-linux-gnu/sys/types.h:197:1: note: candidate found by name
      lookup is 'int64_t'
**intN_t (64, __DI**);
^
/usr/include/x86_64-linux-gnu/sys/types.h:188:15: note: expanded from macro
      '**intN_t'
  typedef int int##N##_t __attribute** ((**mode** (MODE)))
              ^
<scratch space>:154:1: note: expanded from here
int64_t
^
/home/frankenmint/shadow-plugin-bitcoin/build/boost_1_50_0/boost/cstdint.hpp:308:50: note: 
      candidate found by name lookup is 'boost::int64_t'
     typedef  ::boost::long_long_type            int64_t;
                                                 ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.cpp:569:35: error: 
      reference to 'int64_t' is ambiguous
    if ((int64_t)tx.nLockTime < ((int64_t)tx.nLockTime < LOCKTIME_THRESH...
                                  ^
/usr/include/x86_64-linux-gnu/sys/types.h:197:1: note: candidate found by name
      lookup is 'int64_t'
**intN_t (64, __DI**);
^
/usr/include/x86_64-linux-gnu/sys/types.h:188:15: note: expanded from macro
      '**intN_t'
  typedef int int##N##_t __attribute** ((**mode** (MODE)))
              ^
<scratch space>:154:1: note: expanded from here
int64_t
^
/home/frankenmint/shadow-plugin-bitcoin/build/boost_1_50_0/boost/cstdint.hpp:308:50: note: 
      candidate found by name lookup is 'boost::int64_t'
     typedef  ::boost::long_long_type            int64_t;
                                                 ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.cpp:569:80: error: 
      reference to 'int64_t' is ambiguous
  ...< ((int64_t)tx.nLockTime < LOCKTIME_THRESHOLD ? (int64_t)nBlockHeight : ...
                                                      ^
/usr/include/x86_64-linux-gnu/sys/types.h:197:1: note: candidate found by name
      lookup is 'int64_t'
**intN_t (64, __DI**);
^
/usr/include/x86_64-linux-gnu/sys/types.h:188:15: note: expanded from macro
      '**intN_t'
  typedef int int##N##_t __attribute** ((**mode** (MODE)))
              ^
<scratch space>:154:1: note: expanded from here
int64_t
^
/home/frankenmint/shadow-plugin-bitcoin/build/boost_1_50_0/boost/cstdint.hpp:308:50: note: 
      candidate found by name lookup is 'boost::int64_t'
     typedef  ::boost::long_long_type            int64_t;
                                                 ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.cpp:569:80: error: 
      reference to 'int64_t' is ambiguous
  ...< ((int64_t)tx.nLockTime < LOCKTIME_THRESHOLD ? (int64_t)nBlockHeight : ...
                                                      ^
/usr/include/x86_64-linux-gnu/sys/types.h:197:1: note: candidate found by name
      lookup is 'int64_t'
**intN_t (64, __DI**);
^
/usr/include/x86_64-linux-gnu/sys/types.h:188:15: note: expanded from macro
      '**intN_t'
  typedef int int##N##_t __attribute** ((**mode** (MODE)))
              ^
<scratch space>:154:1: note: expanded from here
int64_t
^
/home/frankenmint/shadow-plugin-bitcoin/build/boost_1_50_0/boost/cstdint.hpp:308:50: note: 
      candidate found by name lookup is 'boost::int64_t'
     typedef  ::boost::long_long_type            int64_t;
                                                 ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.cpp:740:5: error: 
      reference to 'int64_t' is ambiguous
    int64_t nValueOut = 0;
    ^
/usr/include/x86_64-linux-gnu/sys/types.h:197:1: note: candidate found by name
      lookup is 'int64_t'
**intN_t (64, __DI**);
^
/usr/include/x86_64-linux-gnu/sys/types.h:188:15: note: expanded from macro
      '**intN_t'
  typedef int int##N##_t __attribute** ((**mode** (MODE)))
              ^
<scratch space>:154:1: note: expanded from here
int64_t
^
/home/frankenmint/shadow-plugin-bitcoin/build/boost_1_50_0/boost/cstdint.hpp:308:50: note: 
      candidate found by name lookup is 'boost::int64_t'
     typedef  ::boost::long_long_type            int64_t;
                                                 ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.cpp:749:9: error: 
      use of undeclared identifier 'nValueOut'
        nValueOut += txout.nValue;
        ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/main.cpp:750:25: error: 
      use of undeclared identifier 'nValueOut'
        if (!MoneyRange(nValueOut))
                        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/init.cpp:563:9: error: 
      reference to 'int64_t' is ambiguous
        int64_t n = 0;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:197:1: note: candidate found by name
      lookup is 'int64_t'
**intN_t (64, __DI**);
^
/usr/include/x86_64-linux-gnu/sys/types.h:188:15: note: expanded from macro
      '**intN_t'
  typedef int int##N##_t __attribute** ((**mode** (MODE)))
              ^
<scratch space>:126:1: note: expanded from here
int64_t
^
/home/frankenmint/shadow-plugin-bitcoin/build/boost_1_50_0/boost/cstdint.hpp:308:50: note: 
      candidate found by name lookup is 'boost::int64_t'
     typedef  ::boost::long_long_type            int64_t;
                                                 ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/init.cpp:564:46: error: 
      use of undeclared identifier 'n'
        if (ParseMoney(mapArgs["-mintxfee"], n) && n > 0)
                                             ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/init.cpp:564:52: error: 
      use of undeclared identifier 'n'
        if (ParseMoney(mapArgs["-mintxfee"], n) && n > 0)
                                                   ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/init.cpp:565:39: error: 
      use of undeclared identifier 'n'
            CTransaction::nMinTxFee = n;
                                      ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/init.cpp:571:9: error: 
      reference to 'int64_t' is ambiguous
        int64_t n = 0;
        ^
/usr/include/x86_64-linux-gnu/sys/types.h:197:1: note: candidate found by name
      lookup is 'int64_t'
**intN_t (64, __DI**);
^
/usr/include/x86_64-linux-gnu/sys/types.h:188:15: note: expanded from macro
      '**intN_t'
  typedef int int##N##_t __attribute** ((**mode** (MODE)))
              ^
<scratch space>:126:1: note: expanded from here
int64_t
^
/home/frankenmint/shadow-plugin-bitcoin/build/boost_1_50_0/boost/cstdint.hpp:308:50: note: 
      candidate found by name lookup is 'boost::int64_t'
     typedef  ::boost::long_long_type            int64_t;
                                                 ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/init.cpp:572:51: error: 
      use of undeclared identifier 'n'
        if (ParseMoney(mapArgs["-minrelaytxfee"], n) && n > 0)
                                                  ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/init.cpp:572:57: error: 
      use of undeclared identifier 'n'
        if (ParseMoney(mapArgs["-minrelaytxfee"], n) && n > 0)
                                                        ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/init.cpp:573:44: error: 
      use of undeclared identifier 'n'
            CTransaction::nMinRelayTxFee = n;
                                           ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/init.cpp:627:5: error: 
      reference to 'int64_t' is ambiguous
    int64_t nStart;
    ^
/usr/include/x86_64-linux-gnu/sys/types.h:197:1: note: candidate found by name
      lookup is 'int64_t'
**intN_t (64, __DI**);
^
/usr/include/x86_64-linux-gnu/sys/types.h:188:15: note: expanded from macro
      '**intN_t'
  typedef int int##N##_t __attribute** ((**mode** (MODE)))
              ^
<scratch space>:126:1: note: expanded from here
int64_t
^
/home/frankenmint/shadow-plugin-bitcoin/build/boost_1_50_0/boost/cstdint.hpp:308:50: note: 
      candidate found by name lookup is 'boost::int64_t'
     typedef  ::boost::long_long_type            int64_t;
                                                 ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/init.cpp:826:9: error: 
      use of undeclared identifier 'nStart'
        nStart = GetTimeMillis();
        ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/init.cpp:905:58: error: 
      use of undeclared identifier 'nStart'
    LogPrintf(" block index %15dms\n", GetTimeMillis() - nStart);
                                                         ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/util.h:117:39: note: 
      expanded from macro 'LogPrintf'
# define LogPrintf(...) LogPrint(NULL, **VA_ARGS**)

```
                                  ^
```

/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/init.cpp:1065:5: error: 
      use of undeclared identifier 'nStart'
    nStart = GetTimeMillis();
    ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/init.cpp:1074:46: error: 
      use of undeclared identifier 'nStart'
           addrman.size(), GetTimeMillis() - nStart);
                                             ^
/home/frankenmint/shadow-plugin-bitcoin/build/bitcoin/src/util.h:117:39: note: 
      expanded from macro 'LogPrintf'
# define LogPrintf(...) LogPrint(NULL, **VA_ARGS**)

```
                                  ^
```

13 errors generated.
make[2]: **\* [src/init.cpp.bc] Error 1
make[2]: **\* Waiting for unfinished jobs....
20 errors generated.
make[2]: **\* [src/main.cpp.bc] Error 1
make[1]: **\* [src/CMakeFiles/shadow-bitcoin-bitcode.dir/all] Error 2
make: **\* [all] Error 2

at a loss as to where to even begin...Also, what steps would I need to take to patch core so I can run simulations on newer software.  I saw you disabled signature checking and proof of work verification to quickly generate blocks, but do you have a guide or a wiki page where you described those  steps?

**Comment by Frankenmint** [comment]
didn't even realize I put this here....okay so Its been a moment I think this has to do with missing boost libraries or them not be recognized.

**Comment by smouldering** [comment]
I had to prefix each int64_t with a '::' (double colon).
