### ISSUE TITLE
wiki should write shadow version (correct build) 

### ISSUE THREAD

**Issue by whywaita** [shadow/shadow-plugin-bitcoin#6]
Hi, Contributers!

I want to build this plugin. but, It is very difficultly.
I don't know which version to use.

after that, I am successful building this plugin.
Using shadow v1.10.2.

I think , This fact should be written on the wiki.

**Comment by whywaita** [comment]
If This issue is no problem, I want to write shadow version on the wiki.

**Comment by robgjansen** [comment]
Thanks for the comment, I added a note to the wiki that this plugin requires shadow version 1.10.2.

**Comment by whywaita** [comment]
Thank you!
